[package]
name = "ds-utils"
version = "0.1.0"
authors = ["Lucas Crespo <ln.crespo@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "1.0.5"
toml = "0.5.8"
thiserror = "1.0.26"
